name: build
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Install JavaFX dependencies for headless testing
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y xvfb libgtk-3-0 libxss1 libasound2
      
      - name: Run tests
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 3
          export MAVEN_OPTS="-Xmx1g -XX:MaxMetaspaceSize=256m"
          export JAVA_TOOL_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw"
          mvn clean test -q

      - name: Generate JaCoCo coverage report
        run: mvn jacoco:report

      - name: Run mutation tests (optional - solo si es necesario)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          export MAVEN_OPTS="-Xmx1g -XX:MaxMetaspaceSize=256m"
          mvn org.pitest:pitest-maven:mutationCoverage -q
      
      - name: Upload coverage report
        if: github.event_name == 'push'
        uses: codecov/codecov-action@v4

  package:
    runs-on: ubuntu-22.04
    needs: build
    if: contains(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Package
        run: mvn clean package -DskipTests -q
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/tp2-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
